POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "New Blog 1", 
    "author": "New Author", 
    "url": "google.com", 
    "likes": 5,
    "userId": "62e1d4e50766e244d19e7865"
}