DELETE http://localhost:3003/api/blogs/62e2f61f2b2bae8449cb8e70
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyZTJmNTM1NTI0Nzc0MjYwMTMwNzE5YyIsImlhdCI6MTY1OTA0NzMwMn0.z5qt6LmP7PkI5acRKvXmNIujEPqlU4vEU-Cyg7fIAmE